version: '3.0'
services:
  reverse:
    image: nginx
    container_name: reverse
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  frontend: 
    build: ./frontend
    container_name: frontend
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MODULE_NAME=app
    networks:
      - app_network

  rmap:
    build: ./rmap
    container_name: rmap
    volumes:
      - ${PWD}/rmap/:/srv/shiny-server/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
